version: '3.7'

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./:/var/www/html:z
        depends_on:
            - php_builder
        networks:
            - project
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: 128M

    php_builder:
        container_name: php_builder
        build:
            context: .
            dockerfile: docker/php/builder/Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - ./docker/php/builder/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www/html:z
        depends_on:
            mysql_builder:
                condition: service_healthy
        networks:
            - project
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: 256M

    mysql_builder:
        container_name: mysql_builder
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - 'mysql_builder:/var/lib/mysql'
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - project
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M

networks:
    project:
        driver: bridge

volumes:
    mysql_builder:
        driver: local
