---
version: "3.7"
services:
  nginx_build:
    container_name: nginx_build
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
    - 80-85:80-85
    volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nodes:/var/www/html/nodes:z
    - ./humanzepola:/var/www/html/humanzepola:z
    depends_on:
    - php_humanzepola
    - php_node_1
    - php_node_2
    networks:
    - project
  php_humanzepola:
    container_name: php_humanzepola
    build:
      context: ./humanzepola/docker/php
      dockerfile: Dockerfile
    volumes:
    - ./humanzepola:/var/www/html:z
    depends_on:
      mysql_humanzepola:
        condition: service_healthy
    networks:
    - project
  mysql_humanzepola:
    container_name: mysql_humanzepola
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - mysql_humanzepola:/var/lib/mysql
    - ./humanzepola/docker/provision/mysql/init:/docker-entrypoint-initdb.d
    networks:
    - project
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -proot
      retries: 3
      timeout: 5s
  php_node_1:
    container_name: php_node_1
    build:
      context: ./nodes/node_1/docker/php/node
      dockerfile: Dockerfile
    volumes:
    - ./nodes/node_1:/var/www/html/nodes/node_1:z
    - ./nodes/node_2:/var/www/html/nodes/node_2:z
    - ./nodes/node_3:/var/www/html/nodes/node_3:z
    depends_on:
      mysql_node_1:
        condition: service_healthy
    networks:
    - project
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
  mysql_node_1:
    container_name: mysql_node_1
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - mysql_node_1:/var/lib/mysql
    - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    networks:
    - project
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -proot
      retries: "3"
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  php_node_2:
    container_name: php_node_2
    build:
      context: ./nodes/node_2/docker/php/node
      dockerfile: Dockerfile
    volumes:
    - ./nodes/node_4:/var/www/html/nodes/node_4:z
    - ./nodes/node_5:/var/www/html/nodes/node_5:z
    depends_on:
      mysql_node_2:
        condition: service_healthy
    networks:
    - project
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
  mysql_node_2:
    container_name: mysql_node_2
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - mysql_node_2:/var/lib/mysql
    - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    networks:
    - project
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -proot
      retries: "3"
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
networks:
  project:
    driver: bridge
volumes:
  mysql_humanzepola:
    driver: local
  mysql_node_1:
    driver: local
  mysql_node_2:
    driver: local
...
