version: '3.7'

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./:/var/www/html/nodes:z
        depends_on:
            - php_humanzepola
        networks:
            - project

    php_node:
        container_name: php_node
        build:
            context: .
            dockerfile: docker/php/node/Dockerfile
        volumes:
            - ./docker/php/node/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www/html/nodes:z
        depends_on:
            mysql_humanzepola:
                condition: service_healthy
        networks:
            - project

    mysql_node:
        container_name: mysql_node
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - 'mysql_node:/var/lib/mysql'
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - project
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s

networks:
    project:
        driver: bridge

volumes:
    mysql_node:
        driver: local
