version: '3.7'

services:
    nginx:
        container_name: nginx
        build:
            context: ./nodes/node_/docker/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nodes/node_:/var/www/html/nodes/node_:z
        depends_on:
            - php_node_
        networks:
            - project
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: 256M

    php_node_:
        container_name: php_node_
        build:
            context: ./nodes/node_/docker/php/node
            dockerfile: Dockerfile
        volumes:
            - ./nodes/node_:/var/www/html/nodes/node_:z
        depends_on:
            mysql_node_:
                condition: service_healthy
        networks:
            - project
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: 256M

    mysql_node_:
        container_name: mysql_node_
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - 'mysql_node_:/var/lib/mysql'
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - project
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M

networks:
    project_:
        driver: bridge

volumes:
    mysql_node_:
        driver: local
